### ISSUE TITLE
Uncaught TypeError: entry.push is not a function

### ISSUE THREAD

**Issue by Laconty** [dschwen/switch-header-source#19]
[Enter steps to reproduce:]

1. Launch atom

Problem is "switchMap"  is plain object(in lib/switch-header-source.coffee)
And when we do switchMap['constructor'] - this returns function-constructor for Object

Solution:
Use ES6 'Map' instead of plain object as hashmap 

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [switch-header-source](https://github.com/dschwen/switch-header-source) package 0.24.4

### Stack Trace

Uncaught TypeError: entry.push is not a function

```
At /Users/roman-mc/.atom/packages/switch-header-source/lib/switch-header-source.coffee:64

TypeError: entry.push is not a function
    at Object.switchMapAdd (/packages/switch-header-source/lib/switch-header-source.coffee:64:13)
    at /packages/switch-header-source/lib/switch-header-source.coffee:96:10
    at Task.get_Task.once [as callback] (/Applications/Atom.app/Contents/Resources/app/node_modules/fuzzy-finder/lib/path-loader.js:23:33)
    at /Applications/Atom.app/Contents/Resources/app/src/task.js:61:78
    at /Applications/Atom.app/Contents/Resources/app/src/task.js:122:31
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/task.js:74:40)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:752:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
atom-beautify 0.30.9 
atom-ide-ui 0.7.0 
autocomplete-clang 0.11.4 
autocomplete-modules 1.8.0 
busy-signal 1.4.3 
color-picker 2.2.5 
docblockr 0.13.4 
emmet 2.4.3 
file-icons 2.1.14 
flow-ide 1.9.0 
git-plus 7.10.0 
gpp-compiler 3.0.7 
highlight-line 0.12.0 
highlight-selected 0.13.1 
hyperclick 0.0.0 
ide-flowtype 0.17.4 
intentions 1.1.5 
js-hyperclick 1.12.2 
language-babel 2.81.0 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-pug 0.0.21 
language-swift 0.5.0 
language-thrift 1.0.2 
linter 2.2.0 
linter-clang 4.1.2 
linter-csslint 2.0.0 
linter-eslint 8.4.0 
linter-flow 5.6.1 
linter-gcc 0.7.1 
linter-swiftc 2.0.0 
linter-ui-default 1.6.10 
linter-write-good 0.9.0 
merge-conflicts 1.4.5 
minimap 4.29.7 
minimap-autohide 0.10.1 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
pigments 0.40.2 
rust-api-docs-helper 0.5.1 
set-syntax 0.4.0 
sort-lines 0.18.0 
switch-header-source 0.24.4 
todo-show 2.1.0 
word-counter 0.0.0 
```

**Comment by dschwen** [comment]
Oh, I see, that is an issue related to the `hasOwnProperty` stuff! Thanks for submitting a PR along with it!!!
